name: deployment
on: 
  push: 
    branches:
      - main
env:
  APP_NAME: My_App
jobs:
  test:
    environment: STAGE
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        node-version: [24.10.0,24.11.0,24.12.0,24.13.0,24.14.0]
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Print Node.js version
        run: node -v
      - name: cache-npm
        id: cached
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cached.outputs.cache-hit!='true'
        run: npm ci
      - name: Run tests
        run: npm test
      # - name: Exit job
      #   run: exit 1
      - name: Log test Status
        if: failure()
        run: echo "$APP_NAME tests run successfully ${{secrets.API_KEY}} ${{vars.URL}}"
  build:
    runs-on: ubuntu-latest
    environment: DEV
    outputs:
      build_file: ${{steps.publish_build.outputs.build_file}}
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.12.0'
      - name: cache-npm
        id: cached
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cached.outputs.cache-hit!='true'
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish Build File Name
        id: publish_build
        run: |
          BUILD_OUTPUT=$(find build/static/js/ -type f -name 'main.*.js' | head -n 1)
          echo "build_file=$BUILD_OUTPUT" >> "$GITHUB_OUTPUT"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: build/
      - name: ENV SECRET
        run: echo "${{secrets.API_KEY}} ${{vars.URL}}"
  deploy:
    runs-on: ubuntu-latest
    environment: PROD
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build
          path: build/
      - name: Get Build File Name
        run: echo "${{ needs.build.outputs.build_file }}"
      - name: Deploy to server
        run: echo "Deploying to server... ${{secrets.API_KEY}} ${{vars.URL}}"
  call_job:
    uses: ./.github/workflows/reusable_job.yml
    secrets: 
      api_key: ${{ secrets.API_KEY }}
    with:
      file_name: "input.xlsx"
      environment: "PROD"
  sub_output:
     needs: call_job
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
       - run: echo "${{ needs.call_job.outputs.status }}"
       - name: Run the first action
         uses: ./.github/actions/cache_deps
       - name: Echo Github Token
         run: echo "${{ secrets.GITHUB_TOKEN }}"
