name: Reusable_job
on: 
  workflow_call:
    inputs:
       file_name:
          required: true
          type: string
       environment:
          required: true
          type: string
jobs:
  job_1:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps: 
       - name: print value
         run: echo "${{ secrets.api_key }}"
       - name: print input
         run: echo "${{ inputs.file_name }}"
