name: Reusable_job
on: 
  workflow_call:
    inputs:
       file_name:
          required: true
          type: string
       environment:
          required: true
          type: string
    secrets:
       api_key:
          required: true
    outputs:
      status:
        description: Job Status
        value: ${{ jobs.job_1.outputs.job_out }}
jobs:
  job_1:
    outputs:
      job_out: ${{ steps.export_out.outputs.my_output }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps: 
       - name: print value
         run: echo "${{ secrets.api_key }}"
       - name: print input
         run: echo "${{ inputs.file_name }}"
       - name: expot value
         id: export_out
         run: echo "my_output=world" >> $GITHUB_OUTPUT
